### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by kennyklee** [marc0l92/obsidian-jira-issue#11]
Just wanna say....this is awesome. Coffee/Beer?

**Comment by marc0l92** [comment]
Thanks for appreciating my work!
I'm doing this mainly because I need it as well for my work.

But if you really want to support it, you can open issues to give me your feedback to make this plugin even better!

I developed this plugin in order to cover my personal use cases, and I know other users have different needs. So let me know how you use this plugin and what are the features that you would like to see in the future!

I just added a "buy me a coffee" link in the readme file in case you want to send me some additional motivation!
