### ISSUE TITLE
JIRA note match problem

### ISSUE THREAD

**Issue by Rick1125** [marc0l92/obsidian-jira-issue#13]
## issue description
1. create a jira-search block with notes column
2. click on one of notes column "+" sign
3. when jira issue keys are duplicated in shortest length, it will match wrong notes
example:
there are 20 issues in search results, PR-1, PR-2 .... PR-20.
if I click on PR-11 and created a note, then PR-1 also shows that PR-11, and same happens on PR-1X(maybe PR-1XX, I didn't test), PR-1 will show all the notes start with PR-1

**Comment by Rick1125** [comment]
Here is the fix:
src/rendering/renderTableColumns.ts
224         const connectedNotes = markdownNotes.filter(n => n.basename === issue.key)

**Comment by marc0l92** [comment]
Thanks for reporting this issue.
I implemented the filter using `startWith` function because I wanted to give more freedom to the notes title.
Examle: In case of issue PR-20 I want to allow people to create notes called: `PR-20 Fix bug on search service`.

But the issue you raised is completely valid. I will modify the filter in order to match notes that starts with the issue key not followed by another number.

**Comment by marc0l92** [comment]
Please update the plugin to version 1.19.0 and let me know if the issue is fixed

**Comment by Rick1125** [comment]
yes, it works. thanks!
