### ISSUE TITLE
Dark mode✅, Inline jira issue ✅, jira-count ✅

### ISSUE THREAD

**Issue by victorhublo** [marc0l92/obsidian-jira-issue#6]
Hello,

Well done for your work on this. It was a good basis to make my own custom plugin. I don't have the time to provide a PR (my code is awful), but I can give you some ideas for the future of your plugin :

# Jira-count
```
```jira-count
project = REF AND status changed to (Done, "Won't Fix", Archived, "Can't Reproduce", "PM Validated") after -14d
```
Which leads to this:
![SCR-20220423-igj](https://user-images.githubusercontent.com/86951202/164892223-42e29987-5e46-487d-b1f4-7f42156766f2.png)

# Caching
All queries can be cached, to have a view of a situation at a specific time. 
![SCR-20220423-igz](https://user-images.githubusercontent.com/86951202/164893072-d096765e-42cc-494d-9609-d98273295c59.png)

**Comment by ahopkins** [comment]
If we are collecting ideas here...

- **Dark mode**

**Comment by marc0l92** [comment]
What do you mean by "Auto-link issues"?
@ahopkins

**Comment by marc0l92** [comment]
@victorhublo in the rendering of jira-count where you thinking to write the query on the side of the number or just the number?
![image](https://user-images.githubusercontent.com/12623073/165603254-ac116a1f-217a-4f04-8189-f024772401c8.png)

**Comment by ahopkins** [comment]
> What do you mean by "Auto-link issues"? @ahopkins

I am not sure if my _ideal_ solution is possible in Obsidian. But here it is:

I would like to type `ABC-1234` and have it automatically converted to a link to that issue: `[ABC-1234](<JIRA>/ABC-1234]`.

Barring this, it would be nice to have some other way to do this. I mimicked the pattern using the QuickAdd plugin so that I can hit a shortcut and insert a link after typing the issue number.

**Comment by zoglesby** [comment]
To add on to what @ahopkins is saying about auto-linking, while I really enjoy the tables and "cards" for things like tracking my sprint work, etc. I also like to take notes in my daily note about what I was doing and the "card" style interface can't really be used in a bullet or as a sub-item and looks out of place with how I take daily notes.

![CleanShot 2022-05-05 at 09 55 11@2x](https://user-images.githubusercontent.com/33433/166938992-8e0daf75-51c3-4361-a015-a386e3008a93.png)

**Comment by marc0l92** [comment]
Having inline jira-issue was a feature that I planned since the begin.
This plugin is mainly based on the features already available in confluence.

I did not implement this feature jet because I'm not really sure what this inline tag should look like.
In markdown there is a standard for fences but not for inline items so I need to make sure to not create conflicts with other plugins.

My idea is to find a simple prefix that is unique enough to not create conflicts. Something like:
```
some text $$AAA-123 other text
```
is rendered in this way
![image](https://user-images.githubusercontent.com/12623073/167028783-b8ce67db-ebbd-4cb4-9e41-c6d2aaae464e.png)

But I'm not sure on the prefix to use...

**Comment by heycalmdown** [comment]
How about to allow the user to add the Jira prefix through the setting dialog? Like `ABC-` as @ahopkins mentioned, or [GitHub did](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources).

Another options is, to recognize the Jira link by the base url which the plugin already has. 

<img width="318" alt="image" src="https://user-images.githubusercontent.com/154198/167034171-cab4d0dd-4bf5-42af-839e-8b4d31290022.png">

**Comment by marc0l92** [comment]
@heycalmdown thanks for this feedback.
I will implement both solutions and add some settings to enable/disable them

**Comment by marc0l92** [comment]
@heycalmdown , @zoglesby , @ahopkins 

Please update the plugin to 1.12.0 and give me some feedbacks on the new inline issues syntax.
You can check the Readme.md to know how to use it.

**Comment by zoglesby** [comment]
@marc0l92 works great, it would be nice if it worked in live preview mode (I don't use reading mode very often), but I will take what I can get. Thanks!

**Comment by marc0l92** [comment]
starting from version 1.18.0 the inline issues are showing in live preview mode as well. Please let me know if it is working fine.

@zoglesby @heycalmdown , @zoglesby @ahopkins @victorhublo

**Comment by heycalmdown** [comment]
It works well like a charm! Thanks!
